name: CI

on:
  push:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: |
          echo ::add-matcher::.github/eslint.json
          npm test
